# 2.1. Data Manipulation

This is a port of Chapter 2 of the infamous [d2l.ai](https://d2l.ai/) textbook to the OrangePi AIpro \(20T\) running the software versions below.

1. CANN 8.5.0
1. MindSpore 2.8.0

Install MindSpore 2.8.0 framework and CANN 8.5.0 Python library dependencies if you haven't already. Use the provided `requirements.txt` if in doubt.

In [1]:
%pip install -r requirements.txt


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## 2.1.1. Getting Started

Check the MindSpore version and that it is installed successfully. There's only 1 NPU chip and core on the OrangePi AIpro \(20T\) development board so let's use it - specify the `device_target` as `Ascend` and `device_id` as `0`.

In [2]:
import mindspore
mindspore.set_device(device_target='Ascend', device_id=0)
mindspore.run_check()

/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/unify_schedule/vector/transdata/common/graph/transdata_graph_info.py:146: SyntaxWarning: invalid escape sequence '\c'
  2. In forward, tiling would not split c1 and c0, find c1\c0 based on t2.
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/unify_schedule/vector/transdata/common/graph/transdata_graph_info.py:172: SyntaxWarning: invalid escape sequence '\c'
  1. Forward: tiling would not split c1\c0\h0, find c1\c0\h1\h0 based on t2
/home/HwHiAiUser/.pyenv/versions/3.12.13/envs/orangepiaipro-20t/lib/python3.12/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/HwHiAiUser/.pyenv/versions/3.12.13/envs/orangep

MindSpore version:  2.8.0
The result of multiplication calculation is correct, MindSpore has been installed on platform [Ascend] successfully!


The `mindspore.ops` library implements many function interfaces including but not limited to tensor operations. Let's focus on the tensor operations provided by `mindspore.ops` in this chapter.

In [3]:
import mindspore.ops as ops

Let's create a range in `[0,12)` using `ops.arange`.

In [4]:
x = ops.arange(12)
x

/usr/local/Ascend/cann-8.5.0/python/site-packages/asc_op_compile_base/asc_op_compiler/ascendc_compile_gen_code.py:161: SyntaxWarning: invalid escape sequence '\w'
  match = re.search(f'{option}=(\w+)', ' '.join(compile_options))
2026-03-22 18:54:47.697279: E external/org_tensorflow/tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute is_closed which is not in the op definition: Op<name=Range; signature=start:Tidx, limit:Tidx, delta:Tidx -> output:Tidx; attr=Tidx:type,default=DT_INT32,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_UINT16, DT_UINT32]> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node Range1}}


Tensor(shape=[12], dtype=Int64, value= [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Let's check the total number of elements in our tensor. Since we created the tensor from the range `[0,12)`, it should be `12`.

In [5]:
x.size

12

The size tells us the total number of elements but not how they are arranged. Let's check how the elements are arranged through the `shape` attribute.

In [6]:
x.shape

(12,)

In our case, the shape of our tensor is `(12,)` - a 1-dimensional tensor \(vector\) with `12` elements.

Let's reshape our tensor to have `3` rows and `4` columns. We need to use the `ops.reshape` function and pass in `(3,4)` for the `shape` argument.

In [7]:
X = ops.reshape(x, (3, 4))
X

Tensor(shape=[3, 4], dtype=Int64, value=
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]])

Check the size and shape of our new tensor `X`.

In [8]:
X.size

12

In [9]:
X.shape

(3, 4)

Same size, but the shape is now `(3,4)` instead of `(12,)`.

We can also have MindSpore infer the remaining dimension of the reshaped tensor by passing in `-1` for the inferred dimension. For example:

In [10]:
X2 = ops.reshape(x, (3, -1))
X3 = ops.reshape(x, (-1, 4))
print(X2)
print(X3)
ops.all(X2 == X3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Tensor(shape=[], dtype=Bool, value= True)

It's common to create zero-initialized tensors of specific shapes as well. Let's create one with shape `(2,3,4)` using `ops.zeros`.

In [11]:
ops.zeros((2, 3, 4))

Tensor(shape=[2, 3, 4], dtype=Float32, value=
[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
  [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
  [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],
 [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
  [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
  [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]])

Similarly, it's common to create tensors with elements initialized to `1` as well, using `ops.ones`.

In [12]:
ops.ones((2, 3, 4))

Tensor(shape=[2, 3, 4], dtype=Float32, value=
[[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
  [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
  [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00]],
 [[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
  [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
  [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00]]])

Another common operation in neural networks is to initialize each element randomly based on the standard normal distribution. Let's create a tensor with shape `(3,4)` whose elements are sampled independently and randomly from the standard normal distribution with mean `0` and standard deviation `1` using `ops.randn`.

In [13]:
ops.randn((3, 4))

Tensor(shape=[3, 4], dtype=Float32, value=
[[-7.75106698e-02, -2.34891772e+00,  6.26021385e-01,  1.63644242e+00],
 [-7.53024817e-01,  4.61631745e-01, -2.42662334e+00, -2.93105096e-01],
 [-1.04235494e+00, -9.63335484e-02, -1.41146874e+00, -5.09876072e-01]])

Finally, we can initialize tensors directly from given values with `mindspore.Tensor`.

In [14]:
mindspore.Tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

Tensor(shape=[3, 4], dtype=Int64, value=
[[2, 1, 4, 3],
 [1, 2, 3, 4],
 [4, 3, 2, 1]])

## 2.1.2. Indexing and Slicing

The usual indexing and slicing rules apply to tensors as they do regular Python lists. For example, let's use indexing to get specific rows of a tensor.

In [15]:
X[-1], X[1:3]

(Tensor(shape=[4], dtype=Int64, value= [ 8,  9, 10, 11]),
 Tensor(shape=[2, 4], dtype=Int64, value=
 [[ 4,  5,  6,  7],
  [ 8,  9, 10, 11]]))

We can modify tensors in-place with indexing and assignment as well.

In [16]:
X[1, 2] = 17
X

Tensor(shape=[3, 4], dtype=Int64, value=
[[ 0,  1,  2,  3],
 [ 4,  5, 17,  7],
 [ 8,  9, 10, 11]])

Assigning multiple elements the same value is also simple. We can combine indexing and assignment across multiple dimensions.

In [17]:
X[:2, :] = 12
X

Tensor(shape=[3, 4], dtype=Int64, value=
[[12, 12, 12, 12],
 [12, 12, 12, 12],
 [ 8,  9, 10, 11]])

## 2.1.3. Operations

The `mindspore.ops` library contains common mathematical functions such as exponentiation, logarithms and trigonometry. Instead of operating on plain numbers or integers, they operate on tensors in an element-wise fashion.

In [18]:
x = ops.arange(12)
ops.exp(x)

Tensor(shape=[12], dtype=Float32, value= [ 1.00000000e+00,  2.71828175e+00,  7.38905621e+00,  2.00855370e+01,  5.45981483e+01,  1.48413162e+02,  4.03428772e+02,  1.09663318e+03,  2.98095801e+03,  8.10308398e+03,  2.20264648e+04,  5.98741406e+04
 ])

Likewise, the usual arithmetic operations `+`, `-`, `*`, `/`, `**` also work on tensors element-wise.

In [19]:
x = mindspore.Tensor([1.0, 2, 4, 8])
y = mindspore.Tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(Tensor(shape=[4], dtype=Float32, value= [ 3.00000000e+00,  4.00000000e+00,  6.00000000e+00,  1.00000000e+01]),
 Tensor(shape=[4], dtype=Float32, value= [-1.00000000e+00,  0.00000000e+00,  2.00000000e+00,  6.00000000e+00]),
 Tensor(shape=[4], dtype=Float32, value= [ 2.00000000e+00,  4.00000000e+00,  8.00000000e+00,  1.60000000e+01]),
 Tensor(shape=[4], dtype=Float32, value= [ 5.00000000e-01,  1.00000000e+00,  2.00000000e+00,  4.00000000e+00]),
 Tensor(shape=[4], dtype=Float32, value= [ 1.00000000e+00,  4.00000000e+00,  1.60000000e+01,  6.40000000e+01]))

We can also concatenate tensors along a given dimension with `ops.cat`. By default, it concatenates along the 1st dimension `axis=0` \(rows\).

In [20]:
from mindspore import dtype as mstype
X = ops.reshape(ops.arange(12, dtype=mstype.float32), (3, 4))
Y = mindspore.Tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(ops.cat((X, Y)))
print(ops.cat((X, Y), axis=0))
print(ops.cat((X, Y), axis=1))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]


We can also apply comparison operators on tensors such as `==`, `!=`, `<`, `>`, `<=`, `>=`. These also operate element-wise and produce boolean tensors as results.

In [21]:
X == Y, X != Y, X < Y, X > Y, X <= Y, X >= Y

(Tensor(shape=[3, 4], dtype=Bool, value=
 [[False,  True, False,  True],
  [False, False, False, False],
  [False, False, False, False]]),
 Tensor(shape=[3, 4], dtype=Bool, value=
 [[ True, False,  True, False],
  [ True,  True,  True,  True],
  [ True,  True,  True,  True]]),
 Tensor(shape=[3, 4], dtype=Bool, value=
 [[ True, False,  True, False],
  [False, False, False, False],
  [False, False, False, False]]),
 Tensor(shape=[3, 4], dtype=Bool, value=
 [[False, False, False, False],
  [ True,  True,  True,  True],
  [ True,  True,  True,  True]]),
 Tensor(shape=[3, 4], dtype=Bool, value=
 [[ True,  True,  True,  True],
  [False, False, False, False],
  [False, False, False, False]]),
 Tensor(shape=[3, 4], dtype=Bool, value=
 [[False,  True, False,  True],
  [ True,  True,  True,  True],
  [ True,  True,  True,  True]]))

We can sum all elements in a tensor with `ops.sum`, returning a new tensor with a single element.

In [22]:
ops.sum(X)

Tensor(shape=[], dtype=Float32, value= 66)

## 2.1.4. Broadcasting

When the shape of 2 tensors do not match up, it's possible to use the broadcasting mechanism to perform binary operations on them. Basically, we copy the elements of each tensor along the dimension with length `1` until both tensors have the same shape, then perform the element-wise operation.

In [23]:
a = ops.reshape(ops.arange(3), (3, 1))
b = ops.reshape(ops.arange(2), (1, 2))
a, b

(Tensor(shape=[3, 1], dtype=Int64, value=
 [[0],
  [1],
  [2]]),
 Tensor(shape=[1, 2], dtype=Int64, value=
 [[0, 1]]))

In [24]:
c = a + b
c

Tensor(shape=[3, 2], dtype=Int64, value=
[[0, 1],
 [1, 2],
 [2, 3]])

In [25]:
A = ops.cat((a, a), axis=1)
B = ops.cat((b, b, b))
C = A + B
A, B, C, ops.all(c == C)

(Tensor(shape=[3, 2], dtype=Int64, value=
 [[0, 0],
  [1, 1],
  [2, 2]]),
 Tensor(shape=[3, 2], dtype=Int64, value=
 [[0, 1],
  [0, 1],
  [0, 1]]),
 Tensor(shape=[3, 2], dtype=Int64, value=
 [[0, 1],
  [1, 2],
  [2, 3]]),
 Tensor(shape=[], dtype=Bool, value= True))

## 2.1.5. Saving Memory

By default, when we compute a new tensor and re-assign it to an existing variable, Python creates a new object in memory. We can observe this effect by calling Python's built-in `id` function which reveals the underlying object ID. We see, that after performing an assignment like `Y = Y + X`, the value of `id(Y)` is different before and after the assignment. This means that `Y` is pointing to a new tensor object after the assignment and the object reference to the original tensor is lost.

In [26]:
before = id(Y)
Y = Y + X
id(Y) == before

False

To avoid wasting memory unnecessarily, it's usually preferred to perform updates on tensors in-place. This has the added benefit that we only need to update the same reference once, instead of finding and updating each reference which would be error-prone as we may accidentally reference stale parameters. In-place tensor updates can be done using standard Python slice notation.

In [27]:
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [28]:
before = id(Y)
Y[:] += X
id(Y) == before

True

## 2.1.6. Conversion to Other Python Objects

Converting a MindSpore tensor to Numpy array and vice versa is simple. MindSpore tensors have the `numpy` method to convert the tensor to a Numpy array and we can pass Numpy arrays directly to the `mindspore.Tensor` constructor to covert a Numpy array to MindSpore tensor.

In [29]:
Y = X.numpy()
Y, type(Y)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 numpy.ndarray)

In [30]:
Z = mindspore.Tensor(Y)
Z, type(Z), ops.all(Z == X)

(Tensor(shape=[3, 4], dtype=Float32, value=
 [[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
  [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00,  7.00000000e+00],
  [ 8.00000000e+00,  9.00000000e+00,  1.00000000e+01,  1.10000000e+01]]),
 mindspore.common.tensor.Tensor,
 Tensor(shape=[], dtype=Bool, value= True))

For tensors containing a single element, we can use the `item` Python built-in method to convert it to a scalar.

In [31]:
z_same_as_x = ops.all(Z == X)
z_same_as_x, z_same_as_x.item()

(Tensor(shape=[], dtype=Bool, value= True), True)

/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: SyntaxWarning: invalid escape sequence '\B'
  Return BN\BH SCH Result
/usr/local/Ascend/cann-8.5.0/python/site-packages/tbe/dsl/classifier/transdata/transdata_classifier.py:223: Sy

## 2.1.7. Summary

We saw how to initialize and manipulate tensors in MindSpore with the following libraries and methods.

1. Invoking functions and methods defined under the `mindspore.ops` module
1. Invoking the `mindspore.Tensor` constructor directly
1. Invoking the overloaded Python operators such as `+`, `-`, `*`, `/`, `**`
1. Converting MindSpore tensors to and from Numpy arrays